version: '3.4'

services:
  library_gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  library_family:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  library_identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  library_package:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  library_parameter:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  postgresql:
    environment:
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_USER: $POSTGRESQL_USER

  postgresql_slave:
    environment:
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_USER: $POSTGRESQL_USER    

  redis:
    command: redis-server --requirepass $REDIS_PASSWORD